server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

---

spring:
  config:
    activate:
      on-profile: h2

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb;MODE=MYSQL;

  jpa:
    hibernate:
      ddl-auto: create-drop

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false